apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  selector:
    matchLabels:
      app: ui-pod
  template:
    metadata:
      labels:
        app: ui-pod
    spec:
      containers:
        - name: ui-container
          image: ragnar:v1
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 80
