name: Push_Master_Pipeline

env:
  APPLICATION_NAME: 'ragnar'
  DEPLOY_PACKAGE_NAME: 'ragnar-deploy-ver-$({ github.sha })'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    # using ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command

      - name: lint
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint # will run `yarn lint` command

      - name: test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test # will run `yarn test` command

      - name: build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command

